GET http://localhost:3030/buscar?filtros=price:>:10000&colunas=id,titulo,price&ordenacao=id:DESC
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MjI2OTg3NDEsIm5iZiI6MTcyMjY5ODc0MSwiZXhwIjoxNzIyNzAyMzQxLCJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjMwMzAiLCJhdWQiOiJodHRwOi8vMTI3LjAuMC4xOjMwMzAiLCJ1aWQiOjJ9.iF4OVUD70EVzvezm2E0_GoMLT4eKvCsQr4A6JTvngNo

###

POST http://localhost:3030/imoveis
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MjI2OTg3NDEsIm5iZiI6MTcyMjY5ODc0MSwiZXhwIjoxNzIyNzAyMzQxLCJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjMwMzAiLCJhdWQiOiJodHRwOi8vMTI3LjAuMC4xOjMwMzAiLCJ1aWQiOjJ9.iF4OVUD70EVzvezm2E0_GoMLT4eKvCsQr4A6JTvngNo


{
    "cidade_id": "1",
    "estado_id": "1",
    "titulo": "Imovel 14 Editado",
    "descricao": "Meu imovel via post",
    "conteudo": "Meu imovel via post",
    "slug": "meu-imovel-via-post",
    "price": "1.99",
    "imovel_area": "20",
    "total_imovel_area": "20",
    "banheiros": "2",
    "quartos": "3",
    "endereco": {
        "endereco": "Rua Nova",
        "bairro": "Sao Bernardo",
        "numero": "28",
        "cep": "65056541"      
    }
}

###
GET http://localhost:3030/imoveis
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MjI2OTg3NDEsIm5iZiI6MTcyMjY5ODc0MSwiZXhwIjoxNzIyNzAyMzQxLCJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjMwMzAiLCJhdWQiOiJodHRwOi8vMTI3LjAuMC4xOjMwMzAiLCJ1aWQiOjJ9.iF4OVUD70EVzvezm2E0_GoMLT4eKvCsQr4A6JTvngNo

###

GET http://localhost:3030/imoveis/1


###

POST http://localhost:3030/imoveis-fotos-upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="imovel"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="fotos[]"; filename="imovel-1.jpg"
Content-Type: image/jpg

< ./data_imagens/imovel-1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="fotos[]"; filename="imovel-2.jpg"
Content-Type: image/jpg

< ./data_imagens/imovel-2.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="fotos[]"; filename="imovel-3.jpg"
Content-Type: image/jpg

< ./data_imagens/imovel-3.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###

POST http://localhost:3030/cadastro
Content-Type: application/json

{
    "nome" : "Cliente 2",  
    "sobrenome" : "Teste",  
    "email" : "teste2@email.com",  
    "senha" : "12345678",  
    "telefone" : "(98) 9999-9999",
    "celular" : "(98) 9 9999-9999"
}

###
POST http://localhost:3030/login
Content-Type: application/json

{
    "email" : "teste@email.com",  
    "senha" : "12345678"
}

###
GET http://localhost:3030/validar-token
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MjI1NTU2MDQsIm5iZiI6MTcyMjU1NTYwNCwiZXhwIjoxNzIyNTU5MjA0LCJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjMwMzAiLCJhdWQiOiJodHRwOi8vMTI3LjAuMC4xOjMwMzAiLCJ1aWQiOjIyfQ.Vk9IorRvnnzyDzLYlBVHKp_rnlJox8Qm9tbhg9LpuJw