GET http://localhost:3030/imoveis
Content-Type: application/json

{
    "cidade_id": "1",
    "estado_id": "1",
    "titulo": "Imovel 13 Editado",
    "descricao": "Meu imovel via post",
    "conteudo": "Meu imovel via post",
    "slug": "meu-imovel-via-post",
    "price": "1.99",
    "imovel_area": "20",
    "total_imovel_area": "20",
    "banheiros": "2",
    "quartos": "3"
}

###

GET http://localhost:3030/imoveis/7